DROP DATABASE IF EXISTS guessgameDB;
CREATE DATABASE guessgameDB;

USE guessgameDB;

CREATE TABLE games(
gameId INT PRIMARY KEY AUTO_INCREMENT,
rounds INT NOT NULL,
answer INT NOT NULL
);

CREATE TABLE rounds (
round INT PRIMARY KEY AUTO_INCREMENT,
guess INT,
result VARCHAR(20) NOT NULL,
dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
gameId INT NOT NULL,
FOREIGN KEY (gameId) REFERENCES games(gameId)
);