DROP DATABASE IF EXISTS guessgametestDB;
CREATE DATABASE guessgametestDB;

USE guessgametestDB;

CREATE TABLE games(
gameId INT PRIMARY KEY AUTO_INCREMENT,
game_status BOOLEAN DEFAULT FALSE,
answer INT NOT NULL
);

CREATE TABLE rounds (
round INT PRIMARY KEY AUTO_INCREMENT,
guess INT,
result VARCHAR(20) NOT NULL,
dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
gameId INT NOT NULL,
FOREIGN KEY (gameId) REFERENCES games(gameId)
);